from prompts.templates import (
    SUPERVISOR_SYSTEM_PROMPT,
    SUPERVISOR_VALIDATION_PROMPT,
    RAG_QUERY_SYSTEM_PROMPT,
    WEB_SEARCH_SYSTEM_PROMPT,
    DRAFT_GENERATION_SYSTEM_PROMPT,
    DRAFT_SELF_CHECK_PROMPT,
)
